name: Build and publish on update 

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
        gpg-private-key: ${{ secrets.GPG_KEY }} 
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - uses: s4u/maven-settings-action@v4.0.0
      with:
        sonatypeSnapshots: true
        apacheSnapshots: true
        servers: |
          [
          {
              "id": "ossrh",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
          },
          {
              "id": "gpg.passphrase",
              "username": "fake",
              "passphrase": "${{ secrets.GPG_PASSPHRASE }}"
          }
          ]
    - name: Deploy
      run: mvn deploy -B -P ci
      working-directory: pom
    - name: Build and analyze
      env:
        # Needed to get PR information, if any
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B -P coverage verify sonar:sonar -Dsonar.projectKey=${{ vars.SONAR_KEY }} -Dsonar.organization=jresearchsoftware
      working-directory: pom
