name: Build and publish on update 

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - uses: s4u/maven-settings-action@v2.5.0
      with:
        sonatypeSnapshots: true
        apacheSnapshots: true
        servers: |
          [{
              "id": "ossrh",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
          }]        
    - name: Package and test
      run: mvn -B package
      working-directory: pom
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "**/target/surefire-reports/*.xml"
    - name: Deploy
      run: mvn -B deploy -Dmaven.test.skip
      working-directory: pom
