name: Build and publish on update 

on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        cache: maven
    - uses: s4u/maven-settings-action@v2.5.0
      with:
        sonatypeSnapshots: true
        apacheSnapshots: true
        servers: |
          [{
              "id": "ossrh",
              "username": "${{ secrets.SONATYPE_USERNAME }}",
              "password": "${{ secrets.SONATYPE_PASSWORD }}"
          }]        
    - name: Deploy
      run: mvn -B deploy
      working-directory: pom
